q = question_number

if q = 1
answerOption1 = ["It defines the functions name"]
answerOption2 = ["It executes the functions code"]
answerOption3 = ["It prints the functions output"]
answerOption4 = ["It specifies the value to be returned by the function"]
elif q = 2
answerOption1 = ["func"]
answerOption2 = ["define"]
answerOption3 = ["def"]
answerOption4 = ["function"]
elif q = 3
answerOption1 = ["A built in function that repeats a statement or a group of statements"]
answerOption2 = ["A way to call a function within itself"]
answerOption3 = ["A loop construct that repeats a statement or group of statements"]
answerOption4 = ["A method for creating anonymous functions"]
elif q = 4
answerOption1 = ["It applies a function to each item in an iterable and returns the results"]
answerOption2 = ["It returns the maximum value from a list"]
answerOption3 = ["It filters elements from an iterable based on a condition"]
answerOption4 = ["It sorts the elements of a list in ascending order"]
elif q = 5
answerOption1 = ["Function signature"]
answerOption2 = ["Function definition"]
answerOption3 = ["Function parameter"]
answerOption4 = ["Function call"]
elif q = 6
answerOption1 = ["option A"]
answerOption2 = ["option A"]
answerOption3 = ["option A"]
answerOption4 = ["option A"]
elif q = 7
answerOption1 = ["option A"]
answerOption2 = ["option A"]
answerOption3 = ["option A"]
answerOption4 = ["option A"]
elif q = 8
answerOption1 = ["option A"]
answerOption2 = ["option A"]
answerOption3 = ["option A"]
answerOption4 = ["option A"]
elif q = 9
answerOption1 = ["option A"]
answerOption2 = ["option A"]
answerOption3 = ["option A"]
answerOption4 = ["option A"]
elif q = 10
answerOption1 = ["option A"]
answerOption2 = ["option A"]
answerOption3 = ["option A"]
answerOption4 = ["option A"]

